import { Head, Link, setLayoutProps, router } from '@inertiajs/react';
import { ArrowLeft, Save } from 'lucide-react';
import { useState } from 'react';
import { SearchableTeacherSelect } from '@/components/SearchableTeacherSelect';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

interface Major {
    id: string;
    code: string;
    name: string;
}

interface Teacher {
    id: string;
    nip: string;
    name: string;
    email: string;
}

interface Props {
    majors: Major[];
    teachers: Teacher[];
}

export default function CreateClassroom({ majors, teachers }: Props) {
    setLayoutProps({
        breadcrumbs: [
            {
                title: 'Manajemen Jurusan & Kelas',
                href: '/admin/majors',
            },
            {
                title: 'Tambah Rombel Kelas',
                href: '/admin/classrooms/create',
            },
        ],
    });

    const [majorId, setMajorId] = useState(majors[0]?.id || '');
    const [grade, setGrade] = useState('10');
    const [section, setSection] = useState('A');
    const [academicYear, setAcademicYear] = useState('2026/2027');
    const [homeroomTeacherId, setHomeroomTeacherId] = useState('');
    const [customName, setCustomName] = useState('');
    const [isCustomName, setIsCustomName] = useState(false);

    const [errors, setErrors] = useState<Record<string, string>>({});
    const [isSubmitting, setIsSubmitting] = useState(false);

    const selectedMajorObj = majors.find((m) => m.id === majorId);
    const autoGeneratedName = selectedMajorObj && section ? `${grade} ${selectedMajorObj.code} ${section.toUpperCase()}` : '';
    const name = isCustomName ? customName : autoGeneratedName;

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        setIsSubmitting(true);

        const payload = {
            id_jurusan: majorId,
            tingkat: grade,
            rombel: section.toUpperCase(),
            nama_kelas: name,
            tahun_ajaran: academicYear,
            id_wali_kelas: homeroomTeacherId || null,
        };

        router.post('/admin/classrooms', payload, {
            onSuccess: () => {
                setIsSubmitting(false);
            },
            onError: (errs) => {
                setErrors(errs);
                setIsSubmitting(false);
            },
        });
    };

    return (
        <>
            <Head title="Tambah Rombel Kelas Baru" />

            <div className="flex flex-col gap-6 p-6 max-w-4xl">
                <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
                    <div>
                        <h1 className="text-3xl font-bold tracking-tight">
                            Tambah Rombel Kelas Baru
                        </h1>
                        <p className="text-muted-foreground">
                            Tentukan jurusan, tingkat, rombel, dan penetapan wali kelas.
                        </p>
                    </div>

                    <Button variant="outline" asChild className="gap-2">
                        <Link href="/admin/majors">
                            <ArrowLeft className="h-4 w-4" />
                            <span>Kembali</span>
                        </Link>
                    </Button>
                </div>

                <Card className="border-none bg-card/50 p-6 shadow-xl backdrop-blur-sm">
                    <form onSubmit={handleSubmit} className="space-y-6">
                        {errors.rombel && (
                            <div className="p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs font-medium dark:bg-rose-950/40 dark:border-rose-900/40 dark:text-rose-300">
                                {errors.rombel}
                            </div>
                        )}

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {/* Jurusan */}
                            <div className="space-y-1.5">
                                <Label htmlFor="id_jurusan" className="font-semibold">Jurusan / Program Keahlian</Label>
                                <select
                                    id="id_jurusan"
                                    value={majorId}
                                    onChange={(e) => setMajorId(e.target.value)}
                                    className="w-full h-10 rounded-lg border border-zinc-200 bg-background/50 px-3 text-sm focus:outline-none dark:border-zinc-800 dark:bg-zinc-900"
                                    required
                                >
                                    {majors.map((m) => (
                                        <option key={m.id} value={m.id}>
                                            {m.code} - {m.name}
                                        </option>
                                    ))}
                                </select>
                                {errors.id_jurusan && (
                                    <p className="text-xs text-rose-500">{errors.id_jurusan}</p>
                                )}
                            </div>

                            {/* Tingkat */}
                            <div className="space-y-1.5">
                                <Label htmlFor="tingkat" className="font-semibold">Tingkat Kelas</Label>
                                <select
                                    id="tingkat"
                                    value={grade}
                                    onChange={(e) => setGrade(e.target.value)}
                                    className="w-full h-10 rounded-lg border border-zinc-200 bg-background/50 px-3 text-sm focus:outline-none dark:border-zinc-800 dark:bg-zinc-900"
                                    required
                                >
                                    <option value="10">Kelas 10 (X)</option>
                                    <option value="11">Kelas 11 (XI)</option>
                                    <option value="12">Kelas 12 (XII)</option>
                                </select>
                                {errors.tingkat && (
                                    <p className="text-xs text-rose-500">{errors.tingkat}</p>
                                )}
                            </div>

                            {/* Rombel Section */}
                            <div className="space-y-1.5">
                                <Label htmlFor="rombel" className="font-semibold">Rombel (Section / Alfabet)</Label>
                                <Input
                                    id="rombel"
                                    placeholder="Contoh: A, B, C"
                                    value={section}
                                    onChange={(e) => setSection(e.target.value.toUpperCase())}
                                    className="h-10 border-zinc-200 bg-background/50 backdrop-blur-sm dark:border-zinc-800 uppercase"
                                    maxLength={5}
                                    required
                                />
                            </div>

                            {/* Tahun Ajaran */}
                            <div className="space-y-1.5">
                                <Label htmlFor="tahun_ajaran" className="font-semibold">Tahun Ajaran</Label>
                                <Input
                                    id="tahun_ajaran"
                                    placeholder="Contoh: 2026/2027"
                                    value={academicYear}
                                    onChange={(e) => setAcademicYear(e.target.value)}
                                    className="h-10 border-zinc-200 bg-background/50 backdrop-blur-sm dark:border-zinc-800"
                                    required
                                />
                                {errors.tahun_ajaran && (
                                    <p className="text-xs text-rose-500">{errors.tahun_ajaran}</p>
                                )}
                            </div>

                            {/* Label Nama Kelas */}
                            <div className="col-span-full space-y-1.5">
                                <div className="flex items-center justify-between">
                                    <Label htmlFor="nama_kelas" className="font-semibold">Nama / Label Kelas (Otomatis)</Label>
                                    <button
                                        type="button"
                                        onClick={() => setIsCustomName(!isCustomName)}
                                        className="text-xs text-primary hover:underline"
                                    >
                                        {isCustomName ? 'Gunakan Format Otomatis' : 'Ubah Nama Manual'}
                                    </button>
                                </div>
                                <Input
                                    id="nama_kelas"
                                    placeholder="Contoh: 12 TKL A"
                                    value={name}
                                    onChange={(e) => {
                                        setIsCustomName(true);
                                        setCustomName(e.target.value);
                                    }}
                                    className="h-10 border-zinc-200 bg-background/50 backdrop-blur-sm dark:border-zinc-800 font-bold"
                                    required
                                />
                                {errors.nama_kelas && (
                                    <p className="text-xs text-rose-500">{errors.nama_kelas}</p>
                                )}
                            </div>

                            {/* Searchable Wali Kelas Dropdown */}
                            <div className="col-span-full space-y-1.5">
                                <SearchableTeacherSelect
                                    teachers={teachers}
                                    value={homeroomTeacherId}
                                    onChange={setHomeroomTeacherId}
                                    label="Penetapan Wali Kelas (Pencarian Nama/NIP)"
                                    placeholder="Pilih Guru Wali Kelas..."
                                    error={errors.id_wali_kelas}
                                />
                            </div>
                        </div>

                        <div className="pt-4 flex items-center justify-end gap-3 border-t border-zinc-200/80 dark:border-zinc-800/80">
                            <Button type="button" variant="outline" asChild>
                                <Link href="/admin/majors">Batal</Link>
                            </Button>
                            <Button
                                type="submit"
                                disabled={isSubmitting}
                                className="gap-2 shadow-lg shadow-primary/20"
                            >
                                <Save className="h-4 w-4" />
                                <span>Simpan Rombel Kelas</span>
                            </Button>
                        </div>
                    </form>
                </Card>
            </div>
        </>
    );
}
